version: '3'
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
              USER_ID: ${USER_ID:-0}
              GROUP_ID: ${GROUP_ID:-0}
        image: php-8.0/app-laravel-insightly-local
        ports:
            - 8080:8080
        environment:
          CONTAINER_ROLE: app
        volumes:
          - ".:/var/www/html"
        networks:
            - insightly

networks:
  insightly:
        driver: bridge
